name: Checar previsão e criar tarefa no Asana

on:
  schedule:
    - cron: '0 12 * * 1' # Segundas às 09h da manhã (UTC-3)
  workflow_dispatch:     # Permite executar manualmente também

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install
      - run: node .
        env:
          OPENWEATHER_KEY: ${{ secrets.OPENWEATHER_KEY }}
          ASANA_TOKEN: ${{ secrets.ASANA_TOKEN }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          SECTION_ID: ${{ secrets.SECTION_ID }}
